### ISSUE TITLE
Create public events

### ISSUE THREAD

**Issue by ErinCall** [code-scouts/green_mercury#17]
Members and mentors should be able to create an event for others to come meet up with them. While we are transitioning off of Meetup, these events should be two-way synced with meetup events using the [Meetup API](http://www.meetup.com/meetup_api/).

An event initially belongs to the person who created it but they can add any number of co-organizers who can edit the event, add other co-organizers, etc.

An event should have a title, a description, a location (with link to map!) and a date and start/end time.

Members and mentors should be able to browse events.

Members and mentors should be able to RSVP yes/no to events. If someone RSVPs no to an event, they shouldn't see it in the index. They should be able to choose to see events they said they weren't going to, though (say, if they change their mind).

**Comment by ErinCall** [comment]
Re @steelerose's [comment](https://github.com/steelerose/green_mercury/commit/3b4b950292c790c36b51450d42faaaa3092a930e#commitcomment-4362348)--

I think it's fine if people can't become organizers until after they've RSVPed. The events I've seen people create on Meetup have mostly been of the form "I am going to be at place X doing Y; come on by if you want." So putting a lot of work into multi-organizer events doesn't seem to make much sense.

And no, now that you mention it, removing organizers doesn't seem important.

**Comment by macmm** [comment]
From above "They should be able to choose to see events they said they weren't going to, though (say, if they change their mind)"

We do not currently have a button to RSVP 'No' - you can RSVP 'Yes', and afterwards, you can cancel your RSVP.

1) Should we add the ability to RSVP 'Yes' or 'No' to an event?

2) If not, we really can't separate out events you have cancelled your RSVP vs events you never RSVP'd to (you either are attending, or have no RSVP for that event).

We think it makes more sense to keep our current method (RSVP 'Yes', or have no RSVP) and in the Public Events Index page, show events you are attending, and all other events - no option to view events you said 'No' to.

Thoughts?

**Comment by ErinCall** [comment]
Ok, I'm sold--let's do what you've described :cat:
