### ISSUE TITLE
Profile types and applications

### ISSUE THREAD

**Issue by ErinCall** [code-scouts/green_mercury#21]
Add is_mentor and is_admin profile types to the user entity_type in the Capture database. A user can be both or either or neither.

A user becomes an admin when they get the is_admin bit set manually.

On registration, a user can apply to become a mentor by filling out an "apply to become a mentor" form. That form makes their application visible to admins, who can approve or deny their request.

On registration, a user can apply to become a member by filling out an "apply to become a member" form. That form makes their application visible to admins, who can approve or deny their request.

Once a user has applied to become a member or mentor, they can see that their request is in review, but can't do much else with the site.

There should be a before_filter in the ApplicationController that does the following things:
- If the user has is_admin set, don't do anything, just let them view the page
- If the user has an approved member or mentor application, don't do anything, just let them view the page
- If the user has an in-progress application, the only page they can view is the "the status of your application" page
- If the user has not made an application, the only page they can view is the "new application" page.

**Comment by pythonchelle** [comment]
Check out #22 -- if is_mentor is set, dues should be waived.

**Comment by ErinCall** [comment]
There's a whole class of behavior that the original description doesn't address: rejecting applications.
- An admin who is reviewing an application should have two buttons: "Approve" and "Reject." If they approve the application, the controller should set `approved_date` to now; if they reject it, the controller should set `rejected_date` to now.
- When viewing the list of applications, admins shouldn't see applications that have been rejected.
- When viewing the list of applications, there should be a link to a page that'll just show rejected applications (in case someone merits reconsideration for whatever reason).
