### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by ErinCall** [code-scouts/green_mercury#23]
Mentors can create new projects, with a title, rich-text description, image, start date, end date, mentor slots, and member slots.

Members and mentors can join projects

Project team members can comment on a project, and reply threadedly to other comments.

[Here are flowcharts and wireframes](http://cl.ly/0t1d2s3Z351w) for the various project pages.

**Comment by ErinCall** [comment]
@jasongrlicky this would benefit from a wireframe before starting.

**Comment by pythonchelle** [comment]
Related to #17, projects should display upcoming events that are specifically related to the project on the project page (upcoming project meetings, etc.). This also means that events should be able to be tied to a project.

**Comment by ErinCall** [comment]
Good call! I made #29 for that.

**Comment by jasongrlicky** [comment]
Wireframes can be found here! :pencil2: :pencil2: :pencil2:  http://cl.ly/0t1d2s3Z351w
